name: Build
on:
  push:
    branches:
      - "**"
jobs:
  build_docker_images:
    name: Build Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build and push the Docker image
        run: |-
          docker build -t ghcr.io/agolzer/public-docker-release .
          if [ "${BRANCH_NAME}" == "master" ] ;
            export TAG=$(grep '^appVersion:' ./charts/public-docker-release/Chart.yaml | tail -n1 | awk '{ print $2}')
            docker tag ${DOCKER_REPO} ${DOCKER_REPO}:$TAG
            docker push ${DOCKER_REPO}:${TAG}
            docker push ${DOCKER_REPO}:latest
          else
            docker push ${DOCKER_REPO}:${BRANCH_NAME}
          fi
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
          DOCKER_REPO: ghcr.io/agolzer/public-docker-release
  publish_helm_chart:
    name: Publish Helm Chart
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          skip_existing: true
          packages_with_index: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
